# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  dockerId: tmahncke
  imageName: jenkins-master

steps:
- script: |
    docker build -t $(dockerId)/$(imageName) -f ./docker/Dockerfile-jenkins-master .
    docker login -u $(dockerId) -p $(pswd)
    docker push $(dockerId)/$(imageName)
  env:
    pswd: $(dockerPassword)